/**
 * Regenerate `client.js` from `client.body.js`.
 *
 * The body is the plain-JS plugin function body of the original plan-graph
 * dynamic plugin (pkg-20). This script wraps it in the web module loader's
 * handoff format: the factory receives the loader's `require`, binds React
 * from the platform module table, provides the `styles.insert` shim the body
 * calls, and captures the body's returned plugin object as `module.exports`.
 *
 * The bundle is plain JavaScript with zero build-time dependencies, so this
 * script is the whole `prepare` step (pnpm runs it after a git install).
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const body = readFileSync(join(root, 'client.body.js'), 'utf8')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

const client = `/* Generated by scripts/build-client.mjs from client.body.js — do not edit. */
window.__ModuleLoader__.load({ id: ${JSON.stringify(pkg.name)}, factory: (require) => {
  var module = { exports: {} }; var exports = module.exports;
  const React = require('react');
  const styles = {
    insert: (css) => {
      if (typeof document === 'undefined') return;
      const tag = document.createElement('style');
      tag.dataset.plugin = ${JSON.stringify(pkg.name)};
      tag.textContent = css;
      document.head.appendChild(tag);
    },
  };
  module.exports = (() => {
${body}
  })();
  return module.exports;
} });
`

writeFileSync(join(root, 'client.js'), client)
console.log(`[dsh-plan-graph] wrote client.js (${client.length} bytes)`)
